"""agent.py: Contains the ACEAgent class, which manages other models.

This module contains the ACEAgent class, which acts as an agent to
process user input and generate responses by orchestrating other models.

classes:
- ACEAgent: The main agent for the ACE program.
"""


class ACEAgent:
    """The main agent for the ACE program.

    This class contains methods to process user input and generate responses
    based on the input, by using other models.

    methods:
    - query: Processes the user's input and generates a response.
    """

    def query(self, user_input: str) -> str:
        """Processes the user's input and generates a response.

        Args:
            user_input (str): The user's input to process.

        Returns:
            str: The response generated by the agent.
        """
        return "Sorry, I don't understand."
