[project]
name = "ace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ddgs>=9.15.0",
    "dotenv>=0.9.9",
    "groq>=1.6.0",
    "markdown>=3.10.3",
    "pygments>=2.20.0",
    "pyqt6>=6.11.0",
    "requests>=2.34.2",
    "selectolax>=0.4.11",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-qt>=4.5.0",
]
