INTENT_PATTERNS = {
    "DUMMY_SKILL": [
        r"run dummy skill with (?P<group1>.*) and (?P<group2>.*)",
        r"run dummy skill with (?P<group1>.*)",
        "run dummy skill",
    ],
    "GREETING_SKILL": [r"^(hi|hello|hey)", r"good (morning|afternoon|evening)"],
    "FAREWELL_SKILL": [r"goodbye", r"bye"],
    "WHO_ARE_YOU_SKILL": [r"(who|what) (are) (you)"],
    "HOW_ARE_YOU_SKILL": [r"(how) (are) (you)"],
    "GET_WEATHER_SKILL": [
        r"(?P<timeframe>current) weather in (?P<location>.*)",
        r"weather (?P<timeframe>today) in (?P<location>.*)",
        r"(?P<timeframe>current) weather at (?P<location>.*)",
        r"weather (?P<timeframe>today) at (?P<location>.*)",
        r"weather in (?P<location>.*) (?P<timeframe>today)",
        r"weather (?P<timeframe>tomorrow) in (?P<location>.*)",
        r"weather (?P<timeframe>tomorrow) at (?P<location>.*)",
        r"(?P<timeframe>tomorrow)'s weather in (?P<location>.*)",
        r"(?P<timeframe>tomorrow)'s weather at (?P<location>.*)",
        r"(?P<timeframe>tomorrow)'s weather",
        r"weather (?P<timeframe>tomorrow)",
        r"(?P<timeframe>current) weather",
        r"weather (?P<timeframe>today)",
    ],
    "TELL_TIME_SKILL": [
        r"what is the time",
        r"what time is it",
        r"tell me the time",
        r"current time",
        r"time (?:.*) in (?P<timevalue>.*) (?P<timeunit>hour|minute|second)",
        r"time in (?P<timevalue>.*) (?P<timeunit>hour|minute|second)",
        r"time now",
    ],
    "TODO_SKILL": [
        r"^(?:todo|task|to-do|to do)s? list",
        r"^(?:todo|task|to-do|to do)s$",
        r"^(?P<action>show|give) (?:todo|task|to-do|to do)s?",
        r"^(?P<action>show|give) me my (?:todo|task|to-do|to do)s?",
        r"^(?P<action>show|give) my (?:todo|task|to-do|to do)s?",
        r"^(?P<action>what)(?:'s| is) on my (?:todo|task|to-do|to do)s?",
        r"^(?P<action>what) do I have to do",
        r"^(?P<action>what) are my (?:tasks|todos|to-dos|to dos)",
        r"^(?P<action>add) a task to my (?:todo|task|to-do|to do)s?",
        r"^(?P<action>add) (?P<task>.*) to my (?:todo|task|to-do|to do)s?",
        r"^(?P<action>add) (?:todo|task|to-do|to do)",
    ],
}
