INTENT_PATTERNS = {
    "DUMMY_SKILL": [
        r"run dummy skill with (?P<group1>.*) and (?P<group2>.*)",
        r"run dummy skill with (?P<group1>.*)",
        "run dummy skill",
    ],
    "GREETING_SKILL": [r"^(hi|hello|hey)", r"good (morning|afternoon|evening)"],
    "FAREWELL_SKILL": [r"goodbye", r"bye"],
    "WHO_ARE_YOU_SKILL": [r"(who|what) (are) (you)"],
    "HOW_ARE_YOU_SKILL": [r"(how) (are) (you)"],
    "GET_WEATHER_SKILL": [
        r"(?P<timeframe>current) weather in (?P<location>.*)",
        r"weather (?P<timeframe>today) in (?P<location>.*)",
        r"(?P<timeframe>current) weather at (?P<location>.*)",
        r"weather (?P<timeframe>today) at (?P<location>.*)",
        r"weather in (?P<location>.*) (?P<timeframe>today)",
        r"weather (?P<timeframe>tomorrow) in (?P<location>.*)",
        r"weather (?P<timeframe>tomorrow) at (?P<location>.*)",
        r"(?P<timeframe>tomorrow)'s weather in (?P<location>.*)",
        r"(?P<timeframe>tomorrow)'s weather at (?P<location>.*)",
        r"(?P<timeframe>tomorrow)'s weather",
        r"weather (?P<timeframe>tomorrow)",
        r"(?P<timeframe>current) weather",
        r"weather (?P<timeframe>today)",
    ],
}
